import { Nullable } from './utils';

export type Registration = {
  id: number;
  slug: string;
  billing_address: Nullable<string>;
  created_at: string;
  updated_at: string;
  completed_at: string;
  discount_code: string;
  email: string;
  job_title: Nullable<string>;
  expires_at: string;
  ip_address: string;
  locale: string;
  metadata: Nullable<Record<string, unknown>>;
  name: string;
  company_name: Nullable<string>;
  payment_reference: Nullable<string>;
  payment_option_name: Nullable<string>;
  phone_number: string;
  registration_type: string;
  reference: string;
  source: Nullable<string>;
  state: string;
  test_mode: boolean;
  cancelled: boolean;
  cancelled_at: Nullable<string>;
  cancelled_by: Nullable<string>;
  free: boolean;
  paid: boolean;
  invoice: boolean;
  manual: boolean;
  imported: boolean;
  refundable: boolean;
  refunded: boolean;
  partially_refunded: boolean;
  receipt_paid: boolean;
  receipt_number: string;
  receipt_id: number;
  payment_incomplete: boolean;
  payment_complete: boolean;
  total: number;
  tickets_count: number;
  consented_at: string;
};
